### Логистическая регрессия

1. Загрузите данные `load_wine` из `sklearn.datasets`. Из данных исключите объекты класса 2.
 Отмасштабируйте признаки, используя класс `StandardScaler` с гиперпараметрами по умолчанию. Обучите логистическую регрессию и оцените важность признаков. Укажите название признака, который оказался наименее значимым.

Обратите внимание, целевое значение лежит по ключу `'target'`, матрица объекты-признаки лежит по ключу `'data'`



In [ ]:
import numpy as np
from sklearn.datasets import load_wine

Загружаем датасет с винами и «складываем» объекты-признаки и целевые значения в отдельные переменные.

In [ ]:
wine = load_wine()
data, target = wine['data'], wine['target']
data, target

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

Находим индексы объектов класса 2 (по целевым значениям).

In [ ]:
indices_of_class_two = np.where(target == 2)
indices_of_class_two

(array([130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177]),)

Убираем объекты класса 2.

In [ ]:
data = np.delete(data, indices_of_class_two, axis=0)
target = np.delete(target, indices_of_class_two, axis=0)
data, target

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.179e+01, 2.130e+00, 2.780e+00, ..., 9.700e-01, 2.440e+00,
         4.660e+02],
        [1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
         3.420e+02],
        [1.204e+01, 4.300e+00, 2.380e+00, ..., 7.900e-01, 2.570e+00,
         5.800e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

Масштабируем признаки, используя `sklearn.preprocessing.StandardScaler` с параметрами по-умолчанию.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(data)
data = scaler.transform(data)
data

array([[ 1.452455  , -0.29441432,  0.30247764, ..., -0.11242761,
         2.04002469,  0.782868  ],
       [ 0.28906609, -0.21455828, -0.67719651, ..., -0.05291788,
         0.94143735,  0.74015178],
       [ 0.24388594,  0.4471061 ,  1.11324246, ..., -0.17193734,
         0.45552372,  1.12459784],
       ...,
       [-1.30353427,  0.18472195,  1.484843  , ..., -0.52899571,
        -1.0867239 , -0.92293343],
       [-0.64842207, -0.38567837, -0.13668663, ..., -1.00507355,
        -0.36841679, -1.27605426],
       [-1.02115832,  2.66025935,  0.13356831, ..., -1.60017084,
        -0.81207706, -0.59829008]])

Делим датасет на обучающую и тестовую выборки.

In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data, target)
data_train, data_test, target_train, target_test

(array([[-0.59194688,  2.80856344,  1.31593367, ..., -0.82654436,
          0.34989032, -1.21055604],
        [ 0.18741075, -1.09297477, -2.16359868, ...,  0.36365022,
          0.4766504 , -0.82041447],
        [ 0.33424624,  0.70949025,  1.78887981, ..., -0.11242761,
         -0.0515166 , -0.15688904],
        ...,
        [ 1.40727485, -0.4313104 ,  0.47138698, ...,  1.01825724,
         -0.28391007,  2.53423341],
        [ 0.50367181, -0.22596628,  0.94433312, ..., -0.82654436,
          0.56115712,  1.15307533],
        [ 0.86511303, -0.12329422,  0.06600457, ...,  0.30414049,
          2.20903813,  0.69743555]]),
 array([[ 1.19640518e-01,  9.34578990e-02,  2.97124517e+00,
          1.83465157e+00,  1.57289086e+00,  1.97513969e-01,
          2.58530736e-01,  1.28622188e+00,  3.11846942e-01,
         -3.79600327e-01,  4.23159950e-01,  5.18903756e-01,
          1.13647076e-01],
        [ 1.44115997e+00,  2.30661115e+00,  5.72732583e-01,
         -1.64889281e+00,  1.83395158e+00,  8.

Обучаем `sklearn.linear_model.LogisticRegression` данным из обучающей выборки и измеряем точность полученной модели на тестовой.

In [ ]:
from sklearn.linear_model import LogisticRegression

estimator = LogisticRegression()
estimator.fit(data_train, target_train)
f'{estimator.score(data_test, target_test):.2%}'

'100.00%'

Находим индекс наименее значимого признака.

In [ ]:
np.argmin(estimator.coef_)

12

2. Загрузите данные `load_wine` из `sklearn.datasets`. Из обучающей части исключите объекты соответствующие классу 2. Не масштабируйте признаки. Обучите логистическую регрессию с гиперпараметрами по умолчанию.
Выберите признак из предложенных, которому соответствует минимальный вес. 

Загружаем датасет с винами и «складываем» объекты-признаки и целевые значения в отдельные переменные.

In [ ]:
wine = load_wine()
data, target = wine['data'], wine['target']
data, target

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

Находим индексы объектов класса 2 (по целевым значениям).

In [ ]:
indices_of_class_two = np.where(target == 2)
indices_of_class_two

(array([130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177]),)

Убираем объекты класса 2.

In [ ]:
data = np.delete(data, indices_of_class_two, axis=0)
target = np.delete(target, indices_of_class_two, axis=0)
data, target

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.179e+01, 2.130e+00, 2.780e+00, ..., 9.700e-01, 2.440e+00,
         4.660e+02],
        [1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
         3.420e+02],
        [1.204e+01, 4.300e+00, 2.380e+00, ..., 7.900e-01, 2.570e+00,
         5.800e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

Делим датасет на обучающую и тестовую выборки.

In [ ]:
data_train, data_test, target_train, target_test = train_test_split(data, target)
data_train, data_test, target_train, target_test

(array([[1.382e+01, 1.750e+00, 2.420e+00, ..., 1.010e+00, 3.260e+00,
         1.190e+03],
        [1.182e+01, 1.720e+00, 1.880e+00, ..., 9.400e-01, 2.440e+00,
         4.150e+02],
        [1.217e+01, 1.450e+00, 2.530e+00, ..., 1.450e+00, 2.230e+00,
         3.550e+02],
        ...,
        [1.242e+01, 2.550e+00, 2.270e+00, ..., 8.600e-01, 3.300e+00,
         3.150e+02],
        [1.430e+01, 1.920e+00, 2.720e+00, ..., 1.070e+00, 2.650e+00,
         1.280e+03],
        [1.305e+01, 1.770e+00, 2.100e+00, ..., 8.800e-01, 3.350e+00,
         8.850e+02]]),
 array([[1.394e+01, 1.730e+00, 2.270e+00, 1.740e+01, 1.080e+02, 2.880e+00,
         3.540e+00, 3.200e-01, 2.080e+00, 8.900e+00, 1.120e+00, 3.100e+00,
         1.260e+03],
        [1.208e+01, 1.390e+00, 2.500e+00, 2.250e+01, 8.400e+01, 2.560e+00,
         2.290e+00, 4.300e-01, 1.040e+00, 2.900e+00, 9.300e-01, 3.190e+00,
         3.850e+02],
        [1.141e+01, 7.400e-01, 2.500e+00, 2.100e+01, 8.800e+01, 2.480e+00,
         2.010e+00, 4.200e-0

Обучаем `sklearn.linear_model.LogisticRegression` данным из обучающей выборки и измеряем точность полученной модели на тестовой.

In [ ]:
estimator = LogisticRegression()
estimator.fit(data_train, target_train)
f'{estimator.score(data_test, target_test):.2%}'

/Users/vsb/.virtualenvs/data-science/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


'96.97%'

Находим индекс наименее значимого признака.

In [ ]:
np.argmin(estimator.coef_)

1

3. Решается задача бинарной классификации. Дана матрица объекты признаки 𝑋 и ответы для объектов  𝑦. Обучите логистическую регрессию и предскажите класс объекта x_new

In [ ]:
X = np.array([[1, 1], [0.3, 0.7], [0, 4], [-2, -7], [0, -2], [-1, -1], [-2, 0]])
y = np.array([1, 1, 1, 0, 0, 0, 0])
x_new = np.array([[-5, 1]])

In [ ]:
estimator = LogisticRegression()
estimator.fit(X, y)
estimator.predict(x_new)

array([0])

### Классификация текстов

4. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. Укажите полученное число признаков.

In [ ]:
import pandas as pd

Загружаем датасет с SMS как CSV-файл с разделитем-табом. Называем колонку с целевым значения (классом сообщения) `target`, а колонку с текстом сообщения `data`.

In [ ]:
sms = pd.read_csv('data/sms/SMSSpamCollection', delimiter='\t', names=['target', 'data'])
sms

target                                               data
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

Разделям датасет на обучающую и тестовую выборки.

In [ ]:
sms_train = sms[:4000]
sms_test = sms[4001:]

Получим векторное представление текстов сообщений из обучающей и тестовой выборки с помощью `sklearn.feature_extraction.text.TfidfVectorizer` с параметрами по-умолчанию.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
vectorizer.fit(sms_train['data'])

vectorizer.transform(sms_train['data'])
vectorizer.transform(sms_test['data'])

len(vectorizer.get_feature_names())

7331

5.  Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer`, помимо слов входящих в тексты, учитывайте биграммы (используйте гиперпараметр `ngram_range`). Укажите полученное число признаков.

Получим векторное представление текстов сообщений из обучающей и тестовой выборки с помощью `sklearn.feature_extraction.text.TfidfVectorizer` с параметром `ngram_range=(2, 2)` для извлечения биграмм (последовательней из двух слов).

In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(2, 2))
vectorizer.fit(sms_train['data'])

vectorizer.transform(sms_train['data'])
vectorizer.transform(sms_test['data'])

len(vectorizer.get_feature_names())

32474

6. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer`, не учитывайте слова, которые встретились меньше 2 раз в обучающей выборке (используйте гиперпараметр `min_df`). Укажите полученное число признаков.

Получим векторное представление текстов сообщений из обучающей и тестовой выборки с помощью `sklearn.feature_extraction.text.TfidfVectorizer` с параметром `min_df=2` для игнорирования слов, которые встречаются меньше двух раз.

In [ ]:
vectorizer = TfidfVectorizer(min_df=2)
vectorizer.fit(sms_train['data'])

vectorizer.transform(sms_train['data'])
vectorizer.transform(sms_test['data'])

len(vectorizer.get_feature_names())

3377

7. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. На полученных векторных представлениях обучите логистическую регрессию и оцените долю правильных ответов на тестовой части. Укажите полученное значение доли правильных ответов.

Получим векторное представление текстов сообщений из обучающей и тестовой выборки с помощью `sklearn.feature_extraction.text.TfidfVectorizer` с параметрами по-умолчанию и обучим `sklearn.linear_model.LogisticRegression` с параметрами по-умолчанию на векторизированных данных.

In [ ]:
data_train, data_test, target_train, target_test = (
    sms_train['data'].values,
    sms_test['data'].values,
    sms_train['target'].values,
    sms_test['target'].values,
)

In [ ]:
vectorizer = TfidfVectorizer()
vectorizer.fit(data_train)

data_train_vectorized = vectorizer.transform(data_train)
data_test_vectorized = vectorizer.transform(data_test)

len(vectorizer.get_feature_names())

7331

In [ ]:
estimator = LogisticRegression()
estimator.fit(data_train_vectorized, target_train)
f'{estimator.score(data_test_vectorized, target_test):.2%}'

'96.94%'